Title: Susan Dania
Logo: Data analysis SQL Excel Power BI Tableau Data visualization Reporting Dashboards Business intelligence Data cleaning Python Communication skills Problem-solving Attention to detail Data validation Data mining Micros.jpg
Theme: jekyll-theme-minimal
